from pathlib import Path

ROOT_DIR = Path(__file__).parent.parent
FILES_DIR = ROOT_DIR / 'resource'
ICON_PATH = FILES_DIR / 'icon.png'

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 12
TEXT_MARGIN = 10
MINIMUM_WIDTH = 500

# Colors
PRIMARY_COLOR = '#440011'
DARKER_PRIMARY_COLOR = "#582F3B"
DARKEST_PRIMARY_COLOR = "#69002C"
SECONDARY_COLOR = "#694001"
DARKER_SECONDARY_COLOR = "#887349"
DARKEST_SECONDARY_COLOR = "#8D5C02"
WHITE_COLOR = '#ffffff'
